### ISSUE TITLE
ksi-tool

### ISSUE THREAD

**Issue by chenxuan199206** [guardtime/ksi-tool#2]
i use the ubuntu，the error is http://download.guardtime.com/ksi/rhel/6/x86_64/repodata/repomd.xml: [Errno -1] pygpgme is not working so repomd.xml can not be verified for guardtime

**Comment by taavi-valjaots** [comment]
Hello!

It seems that You are trying to install Redhat 6 packages under Ubuntu. As there are no packages for Ubuntu see https://github.com/guardtime/ksi-tool#from-source-code how to rebuild KSI tool project under Your system. Note that KSI tool is compatible with Ubuntu but is not tested on regular basis. See https://github.com/guardtime/ksi-tool#compatibility for more information.

Best regards Taavi

**Comment by chenxuan199206** [comment]
Can you explain the principle? I read the document very hard to understand.

**Comment by taavi-valjaots** [comment]
At first You have to install all tools needed to build C projects (gcc make autoconf automake libtool). Next You have to install OpenSSL and Curl - **BOTH** **libraries** and **develop** packages for C header files (openssl openssl-devel curl libcurl-devel). Note that the package names may be different under Ubuntu - use Google for help.

At this point You should be able to build C projects (try Hello World if not sure) and there must be Curl and OpenSSL libraries with C header files in Your machine. To be extra sure search for "curl.h" and "pkcs7.h".

1) Download libksi from https://github.com/guardtime/libksi
2) Goto libksi directory and You should be able to run "./rebuild.sh".
3) Install libksi header files and libraries "make install".
4) Download KSI tool from https://github.com/guardtime/ksi-tool
5) Goto KSI tool directory and You should be able to run "./rebuild.sh".

Make sure that You get the most recent version from libksi and KSI tool available!
